accounts/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from accounts.views import registration_view, activation_view, login_view, logout_view, reset, reset_confirm
from django.views.decorators.cache import cache_page

from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('competitors/twitter', views.save_twitter_competitor_data, name='add-competitor-twitter'),
    path('competitors/analytics', views.competitors_analytics, name= 'competitor-analytics'),
    path('competitors/delete/<id>', views.delete_competitor, name='delete-competitor'),
    path('competitor/<str:name>/reach', views.competitors_data, name='competitors-data'),
    path('competitor/<id>/reach/visualization', views.reach_visualization, name='competitors-reach'),
    path('competitor/<id>/location/visualization', cache_page(60*15)(views.location_visualization), name='competitors-location'),
    path('competitor/<id>/sentiment/visualization', cache_page(60*15)(views.sentiment_visualization), name='competitors-sentiment'),
    path('competitor/<id>/topics/visualization', cache_page(60*15)(views.topics_visualization), name='competitors-topics'),
    path('brand', views.brand, name='account-brand'),
    path('competitor/<id>/visualization/barchart', views.barchart_visualization, name='competitors-barchart'),
    path('', views.home, name='accounts-home'),
    path('competitors/twitter', views.twitter_competitor, name='add-competitor-twitter'),
    path('', views.home, name='home'),
    path('settings', views.settings_view, name='profile-settings'),
    path('upgrade', views.upgrade_plan, name='upgrade-plan'),
    re_path(r'^logout/$', logout_view, name='logout'),
    re_path(r'^login/$', login_view, name='login'),

    re_path(r'^register/$', registration_view, name='register'),

    path('activate/(?P<activation_key>\w+)', activation_view, name='activation_view'),
    path('reset/<uidb64>/<token>/',
         reset_confirm, name='reset_confirm'),
    path('reset/', reset, name='reset'),

    # Change Password URLs for loggedin users:
    path('password_change',
         auth_views.password_change,
         {'post_change_redirect': '/accounts/password_change/done/'},
         name="password_change"),
    path('password_change/done',
         auth_views.password_change_done)

]

accounts/forms.py
from django.forms import ModelForm
from .models import Competitor
from django import forms
from django.conf import settings
from django.contrib.auth import get_user_model
from django.forms.models import inlineformset_factory,modelformset_factory
from django.core.exceptions import NON_FIELD_ERRORS
from django.contrib.auth.models import User
from .models import Profile



class CompetitorTwitterForm(ModelForm):
    class Meta:
        model = Competitor
        fields = ['name', 'description', 'website', 'twitter_id']


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

    def clean_username(self):
        username = self.cleaned_data.get("username")
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            raise forms.ValidationError("Are you sure you are registered? We cannot find this user.")
        return username

    def clean_password(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        try:
            user = User.objects.get(username=username)
        except:
            user = None
        if user is not None and not user.check_password(password):
            raise forms.ValidationError("Invalid Password")
        elif user is None:
            pass
        else:
            return password

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ('user',)

        widgets = {

            'user_type': forms.RadioSelect({'empty_value':False})
        }

class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = '__all__'
        exclude = ('password','last_login','date_joined','username',)



radchoices =(
(True,'Yes'),
(False,'No')
)

class RegistrationForm(forms.ModelForm):
    email = forms.EmailField(label='Your Email')
    password1 = forms.CharField(label='Password', \
                    widget=forms.PasswordInput())
    password2 = forms.CharField(label='Password Confirmation', \
                    widget=forms.PasswordInput())
    code = forms.CharField(max_length=10,required=False)

    accept_terms = forms.BooleanField(widget=forms.CheckboxInput())

    class Meta:
        model = User
        fields = ['email','first_name','last_name','username']
        error_messages = {
           NON_FIELD_ERRORS: {
               'unique_together': "%(model_name)s's %(field_labels)s are not unique.",
           }}


    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match")
        return password2

    def clean_email(self):
        email = self.cleaned_data.get("email")
        user_count = User.objects.filter(email=email).count()
        if user_count > 0:
            raise forms.ValidationError("This email has already been taken. Please use a different email.")
        return email


    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])

        if commit:
            user.save()
        return user

accounts/views.py
from .forms import CompetitorTwitterForm
from django.http import JsonResponse
from .models import Competitor
from django.contrib import messages
from twitterApi.forms import SearchForm
from twitterApi.tasks import save_data, get_competitors_data
from django.shortcuts import get_object_or_404
from django.conf import settings
import googlemaps
import time
import re
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django.shortcuts import render, HttpResponseRedirect, Http404
from django.contrib.auth import logout, login, authenticate
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .util import get_hashtags
from collections import Counter
from django.urls import reverse
import math
from django.conf import settings
from django.contrib.auth.views import password_reset, password_reset_confirm
from accounts.models import EmailConfirmed, Profile
from twitterApi.sentiment import get_tweet_sentiment
from accounts.forms import LoginForm,   RegistrationForm,   UserForm, UserProfileForm
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from twitterApi.utils import extract_location_temp, TwiiterClient
from twitterApi.views import get_token
from collections import Counter


# CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIM)

@login_required()
def home(request):
    template_name = 'accounts/add-profile.html'
    return render(request, template_name)

@login_required()
def brand(request):
    template_name = 'accounts/brand-name.html'
    return render(request, template_name)

@login_required()  
def save_twitter_competitor_data(request):
    if request.method == 'POST':
        form = CompetitorTwitterForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            desc = form.cleaned_data['description']
            webiste = form.cleaned_data['website']
            id_str = form.cleaned_data['twitter_id']
            try:
                save_data = Competitor(
                    user = request.user,
                    name = name,
                    description = desc,
                    website = webiste,
                    twitter_id = id_str
                )
                save_data.save()
                get_competitors_data(user_id = request.user.id, competitor_twitter_id = id_str)
                messages.success(request, "Successfully saved this brand's data")
            except (TypeError, IndexError, IndentationError) as e:
                messages.warning(request, 'The search query did not match any twitter user')
    form = SearchForm()
    return render(request, 'twitter/twitter-results.html', {'form': form})

@login_required()
def competitors_data(request, name):
    template_name = 'accounts/reach.html'
    username = request.user.competitor_set.get(twitter_id = name)
    return render(request, template_name, {'competitor': username})

@login_required()
def competitors_analytics(request):
    template_name = 'competitor/loading.html'
    user_id = request.user.id
    twitter_data = save_data(user_id)
    return render(request, template_name, {'user_id': user_id})

@login_required()
def reach_visualization(request, id):
    template_name = 'accounts/reach-visualization.html'
    competitor = get_object_or_404(request.user.competitor_set, pk=id)
    return render(request, template_name, {'competitor': competitor})

def location_visualization(request, id):
    template_name = 'accounts/map.html'
    competitor = get_object_or_404(request.user.competitor_set, pk=id)
    twitter_id = competitor.twitter_id
    try:
        access_token = get_token(request.user, provider='twitter')
        gmaps = googlemaps.Client(key=settings.GOOGLE_MAPS_API_KEY)
        api = TwiiterClient(
            access_token=access_token['oauth_token'], access_token_secret=access_token['oauth_token_secret'])
        tf = Counter()
        for f in competitor.followersdata_set.all():
            tokens = extract_location_temp(location=f.location)
            tf.update(tokens)
        tags, counts = [], []
        for tag, count in tf.most_common():
            result = gmaps.geocode(tag)
            try:
                tags.append({'lng':result[0]['geometry']['location']['lng'],'lat': result[0]['geometry']['location']['lat']})
                counts.append(count)
            except (IndexError, AttributeError) as e:
                pass            
        
        return render(request, template_name, {
            'competitor': competitor,
            'count': counts,
            'tags': tags
            })
    except Exception as e:
        print('CALLING FROM THIS FUNCTION {}'.format(e))
        return render(request, template_name, {'competitor': competitor})
    return render(request, template_name, {'competitor': competitor})


@login_required()
def sentiment_visualization(request, id):
    analysis = []
    competitor = get_object_or_404(request.user.competitor_set, pk=id)
    access_token = get_token(request.user, provider='twitter')
    api = TwiiterClient(access_token=access_token['oauth_token'], access_token_secret=access_token['oauth_token_secret'])
    template_name = 'accounts/linechart.html'
    context = {
        'competitor': competitor
    }
    try:
        user = api.get_user_data(query=competitor.twitter_id)
        tweets = api.search_tweets(q=user._json['screen_name'])
        print(tweets[0])
        if len(tweets) > 0:
            for tweet in tweets:
                sentiment = get_tweet_sentiment(tweet.text)
                analysis.append(sentiment)
            positive = len([x for x in analysis if x['value'] > 0]) / len(analysis)
            negative = len([x for x in analysis if x['value'] < 0]) / len(analysis)
            neutral = len([x for x in analysis if x['value'] == 0]) / len(analysis)
        context = {
            'competitor': competitor,
            'analysis': analysis,
            'positive': positive,
            'negative': negative,
            'neutral': neutral
        }
        return render(request, template_name, context)
    except Exception as e:
        print(e)
        messages.warning(request, 'Unable to analize your data')
    return render(request, template_name, context)


@login_required()
def topics_visualization(request, id):
    template_name = 'accounts/Listchart.html'
    hashtags = Counter()
    competitor = get_object_or_404(request.user.competitor_set, pk=id)
    context = {
         'competitor': competitor
        }
    try:
        access_token = get_token(request.user, provider='twitter')
        api = TwiiterClient(access_token=access_token['oauth_token'], access_token_secret=access_token['oauth_token_secret'])

        user = api.get_user_data(query=competitor.twitter_id)
        tweets = api.search_tweets(q=user._json['screen_name'])
        tags, counts, add = [], [], 0
        if len(tweets) > 0:
            for tweet in tweets:
                hashtags_in_tweet = get_hashtags(tweet)
                hashtags.update(hashtags_in_tweet)
            for tag, count in hashtags.most_common(12):
                print('{}: {}'.format(tag, count))
                tags.append(tag)
                counts.append(count)
            for c in counts:
                add += int(c)
            percent = [math.ceil((x/add)*100) for x in counts]
        topics = [{'tag': x, 'count': y} for x in tags for y in percent]
        print(topics)
        context = {
         'competitor': competitor,
         'topics': topics,
        }
        print('and we are here')
        return render(request, template_name, context)
    except Exception as e:
        print(e)
        return render(request, template_name, context)



@login_required()
def barchart_visualization(request, id):
    template_name = 'accounts/barchart.html'
    competitor = get_object_or_404(request.user.competitor_set, pk=id)
    return render(request, template_name, {'competitor': competitor})


def twitter_competitor(request):
    pass


def logout_view(request):
    logout(request)
    messages.success(request, "Successfully Logged out. Feel free to login again.", extra_tags='')
    messages.warning(request, "There's a warning.")
    messages.error(request, "There's an error.")
    return HttpResponseRedirect('%s' % (reverse("accounts:login")))


def login_view(request):
    form = LoginForm(request.POST or None)
    btn = "Login"

    if request.GET.get('next') is not None :
        messages.error(request, "You must  be logged-in to continue...")
        redirect_to = request.GET.get('next')
        request.session['redirect_to'] = redirect_to
    else:
        redirect_to = ''

    if (request.user.is_authenticated  ):
        return HttpResponseRedirect(reverse("home"))


    elif request.user.is_authenticated and request.user.is_superuser:
        pass

    if request.POST:


        username = request.POST['username']
        password = request.POST['password']
        get_user = False
        if re.match(r"[\w\.\-\+]+@[\w.-]+.\w+", username):
            try:
                get_user = User.objects.get(email=username)

            except ObjectDoesNotExist as e:
                get_user = False
        if get_user:
            username = get_user.username
            user = authenticate(username=username, password=password)
            if user is None or user.is_anonymous:
                messages.error(request, "Invalid username or  password")
                return HttpResponseRedirect(reverse("accounts:login"))

            login(request, user)

            if not request.user.is_authenticated:
                # login(request, user)
                messages.error(request, "Invalid username or  password")
                return HttpResponseRedirect(reverse("accounts:login"))


        else:
            try:

templates/accounts/login.html
{% extends 'base.html' %}

{% load humanize %}
{% load staticfiles %}
{% load widget_tweaks %}




 {% block content %}




<!-- Start:: main -->
	<main >
		<div class="container mt-112 mb-5">
			<div class="row">
				<div class="col-md-12">

							<div class="col-md-6">
								<div class="form_card">
									<div class="title">
										<p class="med_text text-center f-36 blue_color">  Savant Metrics [Social] </p>
										<p class="text-center light_grey f-14">Let us help you manage your company</p>

                                        <p>

                                            {% if messages %}
								{% for message in messages %}
								<div class="alert alert-warning alert-dismissible" style="margin:auto;">
									<a href="#" class="close" data-dismiss="alert" aria-label="Close">
										&times;
									</a>
									{{ message }}
								</div>
							{% endfor %}
							{% endif %}
                                        </p>
									</div>
									<div class="form-group login_form p-60">
										<form method="post" action="{% url 'accounts:login' %}">
                                             {% csrf_token %}
											<label for="">Username</label>
											<br>
											<input type="text" class="form-control h-47 green-caret" required name="username">
											<div class="form-group mt-4">
												<label for="">Password</label>
												<br>
												<input type="password" class="form-control h-47 green caret" required name="password">
											</div>
											<div class="form-group">
												<div class="checkbox">
													<label class="control control-checkbox green_color">
											            Remember Me
											            <input type="checkbox" checked="checked" />
											            <div class="control_indicator"></div>
											        </label>
													<a href="{% url 'accounts:reset' %}" class="pull-right green_color forgot_password">Forgot Password ?</a>
												</div>
											</div>
											<div class="form-group mt-3  px-3 ">

												<div class="buttons text-center mt-3">
													<button class="btn login_btn_2">Log In</button>
                                                </div>




                                                <div class=" mt-5 ok3">
                                                     <a href="{% url 'accounts:register' %}"  class=" font_color">Don't have an account yet?&nbsp;<strong>Sign Up</strong></a>
                                                </div>

											</div>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- <div class="row no_account">
				<div class="col-md-12 text-right">
					<a href="signup.html" class="text-white ">Don't have an account yet? &nbsp; &nbsp;<strong>Sign Up</strong></a>
				</div>
			</div> -->
		</div>
	</main>
	<!-- END:: Main -->
{% endblock %}

templates/accounts/reach-visualization.html
{% extends '../header.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <title>Select Visualization</title>
    <link rel="stylesheet" href="{% static 'css/page1.css' %}">
</head>
<body>

    <!--  -->

    <!--  -->

{% block pagecontent %}
        
    <nav aria-label="Page navigation example" style="margin: 1% 0 -2% 3%">
      <ul class="pagination">
        <li class="page-item">
          <a class="page-link" href="javascript:history.back()" aria-label="Previous" style="border: none; ">
            <span aria-hidden="true"><i class="fa fa-caret-left fa-3x text-dark" ></i></span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
    </ul>
    </nav>

    <h3 class="big-font">Please Select Visualization</h3>
    <div class="container" style="margin-top: 3%;">
        <div class="row">
            <div class="col-12 col-md-4">
                
                <a href="{% url 'accounts:competitors-barchart' competitor.id %}">
                    <div class="thumbnail">
                        <div class="text-border text-center red" style="height:100px; background-color: rgb(161, 27, 27)">
                            <img src="{% static 'img/bar chart.png' %}" style="height:100%" class="thumbnail-image">
                        </div>
                        <p class="text-content">
                            Bar Chart
                        </p>
                    </div>
                
                    </div>
                </a>

            <div class="col-12 col-md-4">
      
                
                <a href="">
                    <div class="thumbnail">
                        <div class="text-border text-center gray" style="height:100px;background-color: rgb(78, 75, 75)">
                            <img src="{% static 'img/analytics.png' %}" class="thumbnail-image">             
                        </div>
                        <p class="text-content">
                            Line Chart
                        </p>
                    </div>
                </a>

                
              
            </div>

            <div class="col-12 col-md-4">
                <a href="">
                    <div class="thumbnail">
                        <div class="text-border text-center light-green" style="height:100px;background-color: rgb(10, 77, 10)">
                            <img src="{% static 'img/Group.png' %}" class="thumbnail-image">
                        </div>
                        <p class="text-content">
                            Numbers
                        </p>
                    </div>
                </a> 
            </div>
        </div>       
        
    </div>


    {% endblock pagecontent %}

{% block scripts %}
        
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{% endblock scripts %}
</body>
</html>

templates/accounts/reach.html
{% extends '../header.html' %}
{% load staticfiles %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <title>{% block title %} Select A Component {% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/page1.css' %}">
</head>
<body>

{% block pagecontent %}
  
      <!--  -->

    <nav aria-label="Page navigation example" style="margin: 1% 0 -2% 3%">
      <ul class="pagination">
        <li class="page-item">
          <a class="page-link" href="javascript:history.back()" aria-label="Previous" style="border: none; ">
            <span aria-hidden="true"><i class="fa fa-caret-left fa-3x text-dark" ></i></span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
    </ul>
    </nav>

    <h3 class="big-font pb-3">Please Select a Component for {{ competitor.name }}</h3>
    

<div class="container container-fluid container-1">
    
    <div class="row">
      <div class="col-12 col-sm-4">
          <a href="{% url 'accounts:competitors-reach' competitor.id %}">
        <div class="card text-white red mb-3" style="width: 18rem;  border-radius: 0; padding: 10% 0; margin-right: 5%; background-color:brown">
          <div class="card-body">
            <!-- <h5 class="card-title">Danger card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
            <h3 class="text-white text-center text ">R</h3>
          </div>
        </div>
       </a>
        <p class="text-content"> Reach </p>
      </div>

       <div class=" col-12 col-sm-4">
            <a href="#">
        <div class="card text-white gold mb-3" style="width: 18rem;  border-radius: 0; padding: 10% 0; background-color: gold">
          <div class="card-body">
            <!-- <h5 class="card-title">Danger card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
            <h3 class="text-white text-center text ">I</h3>
          </div>
        </div>
            </a>
        <p class="text-content"> Influence</p>
      </div>

       <div class="col-12 col-sm-4">
            <a href="#">
        <div class="card text-white green mb-3 " style="width: 18rem;  border-radius: 0; padding: 10% 0; background-color: green">
          <div class="card-body">
            <!-- <h5 class="card-title">Danger card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
            <h3 class="text-white text-center text ">TA</h3>
          </div>
        </div>
            </a>
        <p class="text-content"> Time of Activity </p>
    </div>
    </div>
</div>

<div class="container container-fluid ">
    
    <div class="row" style="margin-left: -1.4%">
      <div class="col-12 col-sm-4">
            <a href="{% url 'accounts:competitors-topics' competitor.id %}">
        <div class="card text-white gray mb-3" style="width: 18rem;  border-radius: 0; padding: 10% 0; margin-right: 5%; background-color: gray">
          <div class="card-body">
            <!-- <h5 class="card-title">Danger card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
            <h3 class="text-white text-center text ">T</h3>
          </div>
        </div>
            </a>
        <p class="text-content"> Topics </p>
      </div>

       <div class=" col-12 col-sm-4">
            <a href="{% url 'accounts:competitors-location' competitor.id %}">
        <div class="card text-white blue mb-3" style="width: 18rem;  border-radius: 0; padding: 10% 0; background-color: blue">
          <div class="card-body">
            <!-- <h5 class="card-title">Danger card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
            <h3 class="text-white text-center text ">L</h3>
          </div>
        </div>
            </a>
        <p class="text-content"> Location </p>
      </div> 

      <div class="col-12 col-sm-4">
            <a href="#">
        <div class="card text-white gray-light mb-3 " style="width: 18rem;  border-radius: 0; padding: 10% 0; background-color: rgba(168, 155, 155, 0.767)">
          <div class="card-body">
            <!-- <h5 class="card-title">Danger card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
            <h3 class="text-white text-center text ">G</h3>
          </div>
        </div>
            </a>
        <p class="text-content"> Gender</p>
    </div>

    </div>
</div>


<div class="container container-fluid ">
    
    <div class="row" style="margin-left: -1.5%">
      <div class="col-12 col-sm-4">
            <a href="#">
        <div class="card text-white purple mb-3" style="width: 18rem;  border-radius: 0; padding: 10% 0; margin-right: 5%; background-color: purple">
          <div class="card-body">
            <!-- <h5 class="card-title">Danger card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
            <h3 class="text-white text-center text ">L</h3>
          </div>
        </div>
            </a>
        <p class="text-content"> Languages</p>
      </div>

       <div class=" col-12 col-sm-4">
            <a href="#">
        <div class="card text-white yellow mb-3" style="width: 18rem;  border-radius: 0; padding: 10% 0; background-color: yellow">
          <div class="card-body">
            <!-- <h5 class="card-title">Danger card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
            <h3 class="text-white text-center text ">P</h3>
          </div>
        </div>
            </a>
        <p class="text-content"> Popularity</p>
      </div> 
      <div class="col-12 col-sm-4">
            <a href="{% url 'accounts:competitors-sentiment' competitor.id %}">
        <div class="card text-white light-green mb-3 " style="width: 18rem;  border-radius: 0; padding: 10% 0; background-color: rgb(35, 243, 35)">
          <div class="card-body">
            <!-- <h5 class="card-title">Danger card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
            <h3 class="text-white text-center text ">S</h3>
          </div>
        </div>
            </a>
        <p class="text-content"> Sentiments</p>
        </div>
    </div>
</div>
{% endblock pagecontent %}

{% block scripts %}
  
  
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% endblock scripts %}
  </body>
</html>