accounts/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from accounts.views import registration_view, activation_view, login_view, logout_view, reset, reset_confirm
from django.views.decorators.cache import cache_page

from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('competitors/twitter', views.save_twitter_competitor_data, name='add-competitor-twitter'),
    path('competitors/analytics', views.competitors_analytics, name= 'competitor-analytics'),
    path('competitors/delete/<id>', views.delete_competitor, name='delete-competitor'),
    path('competitor/<str:name>/reach', views.competitors_data, name='competitors-data'),
    path('competitor/<id>/reach/visualization', views.reach_visualization, name='competitors-reach'),
    path('competitor/<id>/location/visualization', cache_page(60*15)(views.location_visualization), name='competitors-location'),
    path('competitor/<id>/sentiment/visualization', cache_page(60*15)(views.sentiment_visualization), name='competitors-sentiment'),
    path('competitor/<id>/topics/visualization', cache_page(60*15)(views.topics_visualization), name='competitors-topics'),
    path('brand', views.brand, name='account-brand'),
    path('competitor/<id>/visualization/barchart', views.barchart_visualization, name='competitors-barchart'),
    path('', views.home, name='accounts-home'),
    path('competitors/twitter', views.twitter_competitor, name='add-competitor-twitter'),
    path('', views.home, name='home'),
    path('settings', views.settings_view, name='profile-settings'),
    path('upgrade', views.upgrade_plan, name='upgrade-plan'),
    re_path(r'^logout/$', logout_view, name='logout'),
    re_path(r'^login/$', login_view, name='login'),

    re_path(r'^register/$', registration_view, name='register'),

    path('activate/(?P<activation_key>\w+)', activation_view, name='activation_view'),
    path('reset/<uidb64>/<token>/',
         reset_confirm, name='reset_confirm'),
    path('reset/', reset, name='reset'),

    # Change Password URLs for loggedin users:
    path('password_change',
         auth_views.password_change,
         {'post_change_redirect': '/accounts/password_change/done/'},
         name="password_change"),
    path('password_change/done',
         auth_views.password_change_done)

]

savantsocial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings


from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('twitter/', include('twitterApi.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <--
   # path('account/', include('accounts.urls', namespace='account')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('instagram/', include('instagramApi.urls')),
    path('', views.home, name='home')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


    

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

from django.core.mail import send_mail, EmailMessage
from django.template import Context
from django.urls import reverse

from datetime import datetime
from django.template.loader import render_to_string, get_template


user_types= (
    ('customer','Customer'),
    ('staff','staff'),
)


class EmailConfirmed(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default = 1)
    activation_key = models.CharField(max_length=200)
    confirmed = models.BooleanField(default=False)

    def __unicode__(self):
        vdr = Profile.objects.filter(user=self.user)
        if vdr:
            vendor = vdr[0].user_type
        else:
            vendor = "Admin"
        if self.confirmed == False:
            cnf = vendor + ": Not activated"
        else:
            cnf = vendor + ": Activated"
        theuser = str(self.user.get_full_name()) + " [ " +  str(cnf) + " ]"
        return str(theuser)

    def activate_user_email(self):
        #send email here & render a string
        activation_url = "%s%s" %(settings.SITE_URL, reverse("accounts:activation_view", args=[self.activation_key]))
        context = {
            "activation_key": self.activation_key,
            "activation_url": activation_url,
            "user": self.user.username
        }
        message = render_to_string("accounts/activation_message.txt", context)
        subject = "Activate your Health Intell Account"
        self.email_user(subject, message, settings.DEFAULT_FROM_EMAIL)


    def email_user(self, subject, message, from_email=None, **kwargs):
        try:
            vdr = Profile.objects.filter(user=self.user)


            cc_list = settings.SUPPORT_EMAILS
            #send_mail(subject, message, from_email, [self.user.email], kwargs)
            activation_url = "%s%s" %(settings.SITE_URL, reverse("accounts:activation_view", args=[self.activation_key]))

            ctx = {
            "activation_key": self.activation_key,
            "activation_url": activation_url,
            "user": self.user.get_full_name(),
            'home_url': '%s%s' %(settings.SITE_URL,reverse('home')),
            'login_url': '%s%s' %(settings.SITE_URL,reverse('accounts:login')),
            "vendor_home_url" : '%s%s' %(settings.SITE_URL,reverse('vendor-home')),
            'site_logo_url': "%s%s" %(settings.STATIC_URL,"img/min-logo.png"),
            'email':self.user.email,
            'customer_care_email': "%s" %(settings.CC_EMAIL),
            'customer_care_phone': "%s" %(settings.CC_PHONE),
            'site_name': "%s" %(settings.SITE_NAME),
            'name': self.user.get_full_name(),
            'subject':subject}
            #print self.user.usertype
            if vdr and vdr[0].user_type == 'seller':
                ctx['subject'] = "Activate your Health Intell Account "
                message = get_template('emails/english/account_new_seller.html').render(Context(ctx))
            else:
                ctx['subject'] = "Activate your Health Intell  Account "

                message = get_template('emails/english/account_new_buyer.html').render(Context(ctx))
            new_subject = ctx['subject']
            msg = EmailMessage(new_subject,message, to=[self.user.email], from_email=settings.DEFAULT_FROM_EMAIL,bcc=cc_list,  headers = {'Reply-To': self.user.email })
            msg.content_subtype = 'html'
            msg.send()
        except Exception as e:
            raise e


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default = 1)
    twitter = models.CharField(max_length=255, blank=True, null=True)
    facebook = models.CharField(max_length=255, blank=True, null=True)
    instagram = models.CharField(max_length=255, blank=True, null=True)
    user_type = models.CharField("Signup  As", max_length=20, default='customer', choices=user_types)


    def __unicode__(self):
        return str(self.user_type)


class Competitor(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default = 1)
    name = models.CharField(max_length=255, blank=True, null=True)
    description = models.CharField(max_length=255, blank=True, null=True)
    website = models.CharField(max_length=255, blank=True, null=True)
    twitter_id = models.CharField(max_length=255, blank=True, null=True)
    facebook_id = models.CharField(max_length=255, blank=True, null=True)
    instagram_id = models.CharField(max_length=255, blank=True, null=True)

    def get_absolute_url(self):
        return reverse('accounts:competitors-data', kwargs={'name': self.twitter_id})



class RelatedCompany(models.Model):
    competitor = models.ForeignKey(Competitor, on_delete=models.CASCADE, default = 1)
    name = models.CharField(max_length=255)

savantsocial/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required
def home(request):
    template_name = "savantsocial.html"
    return render(request, template_name)

templates/base.html
{% load staticfiles %}
 <!DOCTYPE html>
<html lang="en">
<head>
	<!-- meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Savant Social  </title>

	<!-- favicon -->
	<link rel="icon" href="{% static '/' %}img/savant.png" sizes="16x16" type="image/png">
	<!-- Bootstrap & Fontawesome CDN -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<!-- External CSS -->
	<link rel="stylesheet" type="text/css" href="{% static '/' %}css/header.css">
	<link rel="stylesheet" type="text/css" href="{% static '/' %}css/login.css">


</head>
<body class="bg_dark-grey">

	<!--  Start::header -->


	<!-- header-2 -->
	<nav class="navbar navbar-expand-lg px-5 py-4 bg_dark-grey navbar-light">
		<a class="navbar-brand" href="{%  url 'home' %}">
			<img src="{% static '/' %}img/savant.png" width="150px">
		</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarTogglerDemo02">
			<ul class="mr-auto"></ul>
			<ul class="navbar-nav  mt-2 mt-lg-0 my-2">
				<li class="nav-item active">
					<a class="nav-link  mr-4 font_color" href="#">Home <span class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item">
					<a class="nav-link  mr-4 font_color" href="#">About</a>
                </li>
                <li class="nav-item">
					<a class="nav-link  mr-4 font_color" href="#">Solution</a>
				</li>
				<li class="nav-item">
					<a class="nav-link  mr-4 font_color" href="#">Contact</a>
				</li>
				<!-- <li class="nav-item">
					<a class="btn nav-link text-white auth-btn bg-success px-5" href="#">Log In</a>
				</li> -->
			</ul>
			<form class="form-inline ">
			</form>
		</div>
	</nav>
	<!-- End:: Header -->
	<!-- Start:: main -->

    {% block content %}

    {% endblock %}





</body>


<!--JS, Popper.js, and jQuery  -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>



</html>

templates/header.html
{% load staticfiles %}
<!DOCTYPE html>

<html>
        <head>

          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
          <meta name="description" content="">
          <meta name="author" content="">
          <!-- Icons -->
          <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
        
          <title>Savant Social Dashboard</title>
        
          <!-- Bootstrap core CSS -->
          <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        
          <!-- Custom css -->
          <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
          <link href="{% static  'css/animate.css' %}" rel="stylesheet">
          <link href="{% static 'css/aos.css' %}" rel="stylesheet">
                <title>
                Savant Social - {% block title %}{% endblock %}
                </title>

  </head>
  <body>


      <nav class="navbar navbar-expand-md bg-dark navbar-dark fixed-top sticky-top flex-md-nowrap p-0">
          <a class="navbar-brand col-xs-3 col-md-2 mr-0 text-white" href="{% url 'home' %}"> Hello {{ user }}</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav navbar-right">
                  
                  <li class="nav-item">
                     <a href="{% url 'accounts:accounts-home' %}" class="profile">
                      <button class="btn btn-sm btn-success btn-plus"> <i class="fa fa-plus fa-fw"></i>Add Profile</button></a> 
                    </li>
                    <li class="nav-item dropdown">
                        <button class="btn btn-user btn-sm" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-user-circle-o fa-2x ml-3" aria-hidden="true"></i> <i class="fa fa-caret-down text-white" style="font-size: 15px"></i>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdown07">
                            <a class="dropdown-item" href="{% url 'accounts:profile-settings' %}">Settings</a>
                            <a class="dropdown-item" href="{% url 'accounts:upgrade-plan' %}">Upgrade Plan</a>
                            <a class="dropdown-item" href="{% url 'accounts:logout' %}">Signout</a>
                        </div>
                  </li>
                  <li class="nav-item">
                      <button class="btn btn-user btn-sm" type="button">
                        <a href="{% url 'twitter-mentions' %}" style="font-size: 20px" class="fa fa-bell-o" aria-hidden="true">
                            <span class="badge badge-info text-white" style="font-size:10px" id="mention-count"></span>
                        </a>
                    </button>
                  </li>
              </ul>
          </div>
      </nav> 


      {% block pagecontent %}



      
      {% endblock pagecontent %}
    </div>


    
    {% block scripts %}
            <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
   
<!--Chat widget-->
<!-- Start of Async Drift Code -->
<script>
    !function() {
      var t;
      if (t = window.driftt = window.drift = window.driftt || [], !t.init) return t.invoked ? void (window.console && console.error && console.error("Drift snippet included twice.")) : (t.invoked = !0, 
      t.methods = [ "identify", "config", "track", "reset", "debug", "show", "ping", "page", "hide", "off", "on" ], 
      t.factory = function(e) {
        return function() {
          var n;
          return n = Array.prototype.slice.call(arguments), n.unshift(e), t.push(n), t;
        };
      }, t.methods.forEach(function(e) {
        t[e] = t.factory(e);
      }), t.load = function(t) {
        var e, n, o, i;
        e = 3e5, i = Math.ceil(new Date() / e) * e, o = document.createElement("script"), 
        o.type = "text/javascript", o.async = !0, o.crossorigin = "anonymous", o.src = "https://js.driftt.com/include/" + i + "/" + t + ".js", 
        n = document.getElementsByTagName("script")[0], n.parentNode.insertBefore(o, n);
      });
    }();
    drift.SNIPPET_VERSION = '0.3.1';
    drift.load('z449gny32ztp');
    </script>
    <!-- End of Async Drift Code -->

    

    <script type="text/javascript">
      $(window).on('load',function(){      
      (function worker() {
        $.ajax({
          url: '{% url "stream_twitter" %}', 
          success: function(data) {
            console.log(data)
            object = document.getElementById('mention-count');
            object.innerHTML = data.data
          },
          error: function(){
            setTimeout(worker, 120000);
          },
          complete: function() {
            // Schedule the next request when the current one's complete
            setTimeout(worker, 120000);
          }
        });
      })();
    });
    </script>


    <!-- Graphs -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>



    <script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>



    {% endblock scripts %} 
  </body>
</html>

templates/savantsocial.html
{% extends 'header.html' %} 
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>

		<meta charset="utf-8">
		<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <title>{% block title %} Dashboard {% endblock %}</title>
  </head>

  <body >

    {% block pagecontent %}
    {% include 'sidebar.html' %}
    <div class="container-fluid">
      <div class="row">
        
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4 ">
        	<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        		<h1 class="h2">Home</h1>
        		<div class="row">
							{% if messages %}
								{% for message in messages %}
								<div class="alert alert-warning alert-dismissible" style="margin:auto;">
									<a href="#" class="close" data-dismiss="alert" aria-label="Close">
										&times;
									</a>
									{{ message }}
								</div>
							{% endfor %}
							{% endif %}
        		</div>
        	</div>

        	<div class="text-center">
        		<h5>Hi {{ user }}, Welcome to Savant Social!</h5>
        		<p class="text-muted">Monitoring your online presence made easy! You have a couple of more things to do to complete setting up your profile. <br>Click on the guide below to get started.</p>
        	</div>
        	<br><br><br>
        	<div class="card-deck text-center">
        		<div class="card"><br>
        			<i class="fa fa-tachometer tach fa-5x"></i>
        			<div class="card-body">
        				<h5 class="card-title">Dashboard Tour</h5>
        				<p class="card-text text-muted">Learn how you can easily use Savant <br>Social.</p><br><br>
        				<a class="btn btn-sm btn-outline-success" href="#"> Start</a>
        			</div>
        		</div>
        		<div class="card"><br>
        			<i class="fa fa-sliders tach fa-5x"></i>
        			<div class="card-body">
        				<h5 class="card-title">Setup Profile</h5>
        				<p class="card-text text-muted">Monitor your brand or product's online presence.</p><br><br>
        				<a class="btn btn-sm btn-outline-success" href="{% url 'accounts:home' %}"> Setup</a>
        			</div>
        		</div>
        		<div class="card"><br><br>
        			<i class="fa fa-users tach fa-4x" aria-hidden="true" ></i>
        			<div class="card-body">
        				<h5 class="card-title">Monitor Competition</h5>
        				<p class="card-text text-muted">Monitor how your competitor's are performing online.</p><br><br>
        				<a class="btn btn-sm btn-outline-success" href="{% url 'accounts:account-brand' %}"> Start</a>
        			</div>
        		</div>
        	</div>

          
        </main>
      </div>
    </div>
   {% endblock %}
  </body>
</html>

templates/sidebar.html
{% load staticfiles %}


<nav class="col-md-2 d-none d-md-block bg-light sidebar">
        <div class="sidebar-sticky">
          <ul class="nav flex-column">
            <li class="nav-item" >
              <a  href="{% url 'accounts:logout' %}"  class="nav-link" style="color: #ff6600" onclick="">
                <i class="fa fa-user fa-fw"></i>
                Signout <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item animated bounceIn">
              <a class="nav-link" href="{% url 'home' %}">
                <i class="fa fa-tachometer fa-fw"></i>
                Dashboard
              </a>
            </li>
            <li class="nav-item animated bounceIn">
                <a class="nav-link" href="{% url 'twitter-mentions' %}">
                  <i class="fa fa-bullhorn fa-fw"></i>
                  Mentions
                </a>
              </li>
            </li>
            </ul>
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Analytics</span>
            <a class="d-flex align-items-center text-muted" href="#">
            </a>
          </h6>
          <ul class="nav flex-column mb-2">
            <li class="nav-item animated bounceIn">
              <a class="nav-link " href="{% url 'twitter_followers_data' %}">
                <i class="fa fa-twitter fa-fw"></i>
                Twitter
              </a>
            </li>
            <!--
            <li class="nav-item animated bounceIn">
              <a class="nav-link" href="facebook.html">
                <i class="fa fa-facebook fa-fw"></i>
                Facebook
              </a>
            </li>
            <li class="nav-item animated bounceIn">
              <a class="nav-link" href="instagram.html">
                <i class="fa fa-instagram fa-fw"></i>
                Instagram
              </a>
            </li> 
          -->
            </ul>
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                <span>Competition</span>
                <a class="d-flex align-items-center text-muted" href="#">
                </a>
            </h6>
            <ul class="nav flex-column mb-2">
              {% for comeptitor in user.competitor_set.all %}
            <li class="nav-item animated bounceIn">
              <a class="nav-link" href="{{ comeptitor.get_absolute_url }}">
                <span data-feather="layers"></span>
                {{ comeptitor.name }}
              </a>
            </li>
            {% endfor %}
          </ul>
          
          <button class="btn btn-outline-danger btn1  dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Help</button>
          <div class="dropdown-menu" aria-labelledby="dropdown07">
            <a class="dropdown-item" href="#">Getting Started</a>
            <a class="dropdown-item" href="#">FAQ</a>
            <a class="dropdown-item" href="{% url 'accounts:logout' %}">Signout</a>
          </div>
        </div>
        </div>
      </nav>